name: Build Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    outputs:
      chrome_zip_name: ${{ steps.set_outputs.outputs.chrome_zip_name }}
      firefox_zip_name: ${{ steps.set_outputs.outputs.firefox_zip_name }}
      version: ${{ steps.package_version.outputs.VERSION }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: package-lock.json
    
    - name: Extract version from package.json
      id: package_version
      run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build extension
      run: npm run build
    
    - name: Create Chrome ZIP
      run: npm run zip
    
    - name: Create Firefox ZIP
      run: npm run zip:firefox
    
    - name: Set output variables
      id: set_outputs
      run: |
        chrome_zip_file=$(ls .output/chrome-mv3/zip/*.zip | head -n 1)
        firefox_zip_file=$(ls .output/firefox-mv3/zip/*.zip | head -n 1)
        echo "chrome_zip_name=$(basename $chrome_zip_file)" >> $GITHUB_OUTPUT
        echo "firefox_zip_name=$(basename $firefox_zip_file)" >> $GITHUB_OUTPUT
    
    - name: Upload Chrome build artifact
      uses: actions/upload-artifact@v4
      with:
        name: chrome-extension-v${{ steps.package_version.outputs.VERSION }}
        path: .output/chrome-mv3/zip/*.zip
        retention-days: 1
    
    - name: Upload Firefox build artifact
      uses: actions/upload-artifact@v4
      with:
        name: firefox-extension-v${{ steps.package_version.outputs.VERSION }}
        path: .output/firefox-mv3/zip/*.zip
        retention-days: 1

  release:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download Chrome artifact
      uses: actions/download-artifact@v4
      with:
        name: chrome-extension-v${{ needs.build.outputs.version }}
        path: ./chrome-extension
    
    - name: Download Firefox artifact
      uses: actions/download-artifact@v4
      with:
        name: firefox-extension-v${{ needs.build.outputs.version }}
        path: ./firefox-extension
    
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ needs.build.outputs.version }}
        name: Release v${{ needs.build.outputs.version }}
        draft: false
        prerelease: false
        files: |
          ./chrome-extension/*.zip
          ./firefox-extension/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 